# syntax=docker/dockerfile:1.7

# ----------------------------------------------------------------------------
# Shufazidian — Next.js 16 + better-sqlite3 on Fly.io
# ----------------------------------------------------------------------------

ARG NODE_VERSION=22-bookworm-slim

# ---- 1. deps -----------------------------------------------------------------
FROM node:${NODE_VERSION} AS deps
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
      python3 \
      make \
      g++ \
      ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm ci --include=dev

# ---- 2. builder --------------------------------------------------------------
FROM node:${NODE_VERSION} AS builder
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# FIX: Pre-warm the database sequentially before Next.js parallel workers start.
# This prevents the 'SQLITE_BUSY' lock crash during 'npm run build'.
RUN node -e "\
  try { \
    const db = require('better-sqlite3')('data/shufazidian.db'); \
    db.pragma('journal_mode = WAL'); \
    db.close(); \
    console.log('✅ DB pre-warmed for build'); \
  } catch(e) { \
    console.log('⚠️ DB pre-warm skipped:', e.message); \
  }"

RUN npm run build

# ---- 3. runner ---------------------------------------------------------------
FROM node:${NODE_VERSION} AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# FIX: Matched PORT to internal_port = 8080 defined in your fly.toml
ENV PORT=8080
ENV HOSTNAME=0.0.0.0

RUN groupadd --system --gid 1001 nodejs \
 && useradd  --system --uid 1001 --gid nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static     ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public           ./public
COPY --from=builder --chown=nextjs:nodejs /app/drizzle          ./drizzle
COPY --from=builder --chown=nextjs:nodejs /app/scripts/fly-migrate.mjs ./scripts/fly-migrate.mjs
COPY --from=builder --chown=nextjs:nodejs /app/scripts/fly-start.sh    ./scripts/fly-start.sh
RUN chmod +x ./scripts/fly-start.sh

# FIX: Copy the entire data directory to capture the DB and any WAL sidecars 
# generated by the Next.js workers during the build phase.
RUN mkdir -p ./data && chown nextjs:nodejs ./data
COPY --from=builder --chown=nextjs:nodejs /app/data/ ./data/

USER nextjs

EXPOSE 8080

CMD ["./scripts/fly-start.sh"]